#pragma once

#include <string>
#include <vector>
#include <cstdint>
#include <chrono>
#include <algorithm>
#include <glaze/glaze.hpp>

namespace moltcat::memory {

/**
 * @brief Memory type
 *
 * Define four memory types, simulating human memory system
 */
enum class MemoryType : uint8_t {
    EPISODIC = 0,   // Episodic memory (events, task execution process, conversation history)
    SEMANTIC = 1,   // Semantic memory (knowledge, concepts, rules, facts)
    PROCEDURAL = 2, // Procedural memory (skills, operation methods, best practices)
    WORKING = 3     // Working memory (temporary state, session level, short-term memory)
};

/**
 * @brief Memory visibility
 *
 * Define three visibility levels, implementing access control and layered architecture
 */
enum class MemoryVisibility : uint8_t {
    PRIVATE = 0,    // Private (only visible to creator Agent)
    SHARED = 1,     // Shared (visible to specified Agents, supports collaboration)
    GLOBAL = 2      // Global (visible to all Agents, such as public knowledge base)
};

/**
 * @brief Memory entry
 *
 * Complete memory data structure, including content, metadata, access control, etc.
 * Supports JSON serialization and semantic retrieval
 */
struct MemoryEntry {
    // ========== Basic Information ==========

    /**
     * @brief Memory unique identifier
     *
     * Format: mem_<uuid>
     * Example: mem_a1b2c3d4-e5f6-7890-abcd-ef1234567890
     */
    std::string memory_id;

    /**
     * @brief Creator Agent ID
     *
     * Records the Agent instance ID that created this memory
     */
    std::string owner_agent_id;

    /**
     * @brief Memory type
     *
     * Distinguishes different types of memory, affecting storage strategy and retrieval method
     */
    MemoryType type{MemoryType::EPISODIC};

    /**
     * @brief Memory visibility
     *
     * Controls which Agents can access this memory
     */
    MemoryVisibility visibility{MemoryVisibility::PRIVATE};

    // ========== Content ==========

    /**
     * @brief Memory content
     *
     * Stored in JSON format, supports arbitrary complex structures
     * Examples:
     * - Episodic memory: {"event": "task_completed", "result": "success"}
     * - Semantic memory: {"knowledge": "Python lists are mutable"}
     * - Procedural memory: {"skill": "code_review", "steps": [...]}
     */
    glz::json_t content;

    /**
     * @brief Vector embedding
     *
     * Vector representation for semantic retrieval (usually generated by embedding model)
     * Dimension depends on model, e.g., OpenAI text-embedding-3-small is 1536 dimensions
     *
     * Note: Phase 2 only reserves this field, actual embedding generation will be implemented in later phases
     */
    std::vector<float> embedding;

    // ========== Metadata ==========

    /**
     * @brief Creation time (millisecond timestamp)
     *
     * Unix timestamp, unit: milliseconds
     */
    uint64_t created_at{0};

    /**
     * @brief Last access time (millisecond timestamp)
     *
     * Used for LRU cache eviction strategy
     */
    uint64_t last_accessed_at{0};

    /**
     * @brief Access count
     *
     * Used for memory importance assessment and access frequency statistics
     */
    uint32_t access_count{0};

    /**
     * @brief Importance score [0.0, 1.0]
     *
     * Affects memory retention strategy:
     * - High importance memories are retained long-term
     * - Low importance working memories are periodically cleaned
     */
    float importance{0.5f};

    // ========== Association Information ==========

    /**
     * @brief Associated task ID
     *
     * If memory is related to a specific task, record the task ID
     * Used for task context reconstruction and review
     */
    std::string task_id;

    /**
     * @brief Associated session ID
     *
     * Records the belonging session/conversation, supports session-level memory management
     */
    std::string session_id;

    /**
     * @brief Tag list
     *
     * Used for tag-based retrieval and classification
     * Examples: ["code_review", "bug_fix", "optimization"]
     */
    std::vector<std::string> tags;

    // ========== Access Control ==========

    /**
     * @brief Allowed reader Agent ID list
     *
     * Only valid for SHARED type memories
     * PRIVATE type: ignore this field
     * GLOBAL type: this field is empty
     */
    std::vector<std::string> allowed_readers;

    // ========== Utility Methods ==========

    /**
     * @brief Check if specified Agent has permission to access this memory
     */
    [[nodiscard]] auto is_accessible_by(std::string_view agent_id) const -> bool {
        switch (visibility) {
            case MemoryVisibility::PRIVATE:
                // Only creator can access
                return agent_id == owner_agent_id;

            case MemoryVisibility::SHARED:
                // Creator or Agents in allowed list can access
                if (agent_id == owner_agent_id) {
                    return true;
                }
                return std::find(allowed_readers.begin(), allowed_readers.end(), agent_id)
                       != allowed_readers.end();

            case MemoryVisibility::GLOBAL:
                // All Agents can access
                return true;

            default:
                return false;
        }
    }

    /**
     * @brief Update access statistics
     */
    auto update_access_stats() noexcept -> void {
        ++access_count;
        last_accessed_at = get_current_time_ms();
    }

    /**
     * @brief Get current timestamp (milliseconds)
     */
    [[nodiscard]] static auto get_current_time_ms() noexcept -> uint64_t {
        auto now = std::chrono::system_clock::now();
        auto duration = now.time_since_epoch();
        return std::chrono::duration_cast<std::chrono::milliseconds>(duration).count();
    }
};

} // namespace moltcat::memory

// Glaze serialization support
template <>
struct glz::meta<moltcat::memory::MemoryType> {
    static constexpr auto value = glz::enumerate<
        "EPISODIC",
        moltcat::memory::MemoryType::EPISODIC,
        "SEMANTIC",
        moltcat::memory::MemoryType::SEMANTIC,
        "PROCEDURAL",
        moltcat::memory::MemoryType::PROCEDURAL,
        "WORKING",
        moltcat::memory::MemoryType::WORKING
    >;
};

template <>
struct glz::meta<moltcat::memory::MemoryVisibility> {
    static constexpr auto value = glz::enumerate<
        "PRIVATE",
        moltcat::memory::MemoryVisibility::PRIVATE,
        "SHARED",
        moltcat::memory::MemoryVisibility::SHARED,
        "GLOBAL",
        moltcat::memory::MemoryVisibility::GLOBAL
    >;
};

template <>
struct glz::meta<moltcat::memory::MemoryEntry> {
    using T = moltcat::memory::MemoryEntry;
    static constexpr auto value = glz::object<
        "memory_id", &T::memory_id,
        "owner_agent_id", &T::owner_agent_id,
        "type", &T::type,
        "visibility", &T::visibility,
        "content", &T::content,
        "embedding", &T::embedding,
        "created_at", &T::created_at,
        "last_accessed_at", &T::last_accessed_at,
        "access_count", &T::access_count,
        "importance", &T::importance,
        "task_id", &T::task_id,
        "session_id", &T::session_id,
        "tags", &T::tags,
        "allowed_readers", &T::allowed_readers
    >;
};
